"""Data-integrity / audit engine (Feature A4) — pure-Python.

Computes the audit panel's content from the run artifacts (fetch_status.json,
screen_run.json, the parcels GeoJSON) joined with config.data_integrity. The
license-restricted ERCOT GIS Report is surfaced as a GOVERNANCE signal, never
displayed raw. Mirrors portfolio.py: read artifacts -> build -> write.
"""

from __future__ import annotations

from typing import Any


def layer_freshness(
    fetch_status: dict[str, Any], run_meta: dict[str, Any], cfg: dict[str, Any]
) -> list[dict[str, Any]]:
    """Public layers (config map x fetch counts x run time) + the restricted ERCOT row."""
    di = cfg["data_integrity"]
    retrieved = (run_meta or {}).get("run_utc")
    rows: list[dict[str, Any]] = []
    for layer, meta in di["layers"].items():
        fs = (fetch_status or {}).get(layer) or {}
        rows.append({
            "layer": layer, "source": meta["source"], "license": meta["license"],
            "role": meta["role"], "status": "live" if fs.get("ok") else "pending",
            "count": fs.get("count"), "retrieved": retrieved,
        })
    for _, meta in di["restricted"].items():
        rows.append({
            "layer": meta["source"], "source": meta["source"], "license": meta["license"],
            "role": meta["role"], "status": "backend-abstracted", "count": None,
            "retrieved": retrieved,
        })
    return rows


def run_summary(run_meta: dict[str, Any]) -> dict[str, Any]:
    rm = run_meta or {}
    return {
        "run_utc": rm.get("run_utc"),
        "parcel_count": rm.get("parcel_count"),
        "shortlist_count": rm.get("shortlist_count"),
        "criteria_status": rm.get("criteria_status") or {},
        "lenses": rm.get("lenses") or {},
        "verdict_layer": rm.get("verdict_layer"),
    }


def provenance(fetch_status: dict[str, Any], run_meta: dict[str, Any]) -> dict[str, Any]:
    fetched = ((fetch_status or {}).get("parcels") or {}).get("count")
    final = (run_meta or {}).get("parcel_count")
    return {
        "fetched": fetched,
        "final": final,
        "shortlist": (run_meta or {}).get("shortlist_count"),
        "note": "Parcel records fetched -> distinct parcels after the ≥50-acre floor + "
                "footprint de-duplication. Geometry/infrastructure real + sourced; "
                "ownership + deal pipeline synthetic.",
    }


def field_completeness(fc: dict[str, Any], cfg: dict[str, Any]) -> list[dict[str, Any]]:
    di = cfg["data_integrity"]
    props = [f["properties"] for f in fc.get("features", [])]
    total = len(props) or 1
    warn = di["null_rate_warn"]
    rows = []
    for field in di["audit_fields"]:
        nulls = sum(1 for p in props if p.get(field) is None)
        rate = nulls / total
        rows.append({"field": field, "null_rate": round(rate, 4), "ok": rate <= warn})
    return rows


def build_audit(
    fc: dict[str, Any], fetch_status: dict[str, Any],
    run_meta: dict[str, Any], cfg: dict[str, Any],
) -> dict[str, Any]:
    di = cfg["data_integrity"]
    completeness = field_completeness(fc, cfg)
    run = run_summary(run_meta)
    anomalies: list[str] = []
    for r in completeness:
        if not r["ok"]:
            anomalies.append(f"{r['field']}: {round(r['null_rate'] * 100)}% null across parcels.")
    for lens, status in (run.get("lenses") or {}).items():
        if "neutral" in str(status) or "needs" in str(status):
            anomalies.append(f"{lens} lens: {status}.")
    return {
        "_note": "Generated by pipeline/audit.py — the screen audits its own provenance, "
                 "license posture, and field completeness. Synthetic ownership/pipeline; "
                 "real, sourced geospatial layers.",
        "run": run,
        "provenance": provenance(fetch_status, run_meta),
        "layers": layer_freshness(fetch_status, run_meta, cfg),
        "completeness": completeness,
        "governance_note": di["governance_note"],
        "reconciled": di["reconciled"],
        "anomalies": anomalies,
    }


def write_audit(fc: dict[str, Any], cfg: dict[str, Any],
                fetch_status_path, run_meta_path, out_path) -> int:
    """Read fetch_status.json + screen_run.json, compute, write integrity.json.
    Null-safe if an artifact is missing (fresh clone). Returns the layer count."""
    import json
    from pathlib import Path

    def _load(p):
        path = Path(p)
        return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}

    data = build_audit(fc, _load(fetch_status_path), _load(run_meta_path), cfg)
    Path(out_path).write_text(json.dumps(data, ensure_ascii=False, indent=0), encoding="utf-8")
    return len(data["layers"])
